# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 648)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/files/static/image/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setStyleSheet("font: 87 9pt \"Arial\";")
        self.CentralWidget.setObjectName("CentralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.CentralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 1111, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.TopColumnLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.TopColumnLayout.setContentsMargins(0, 0, 0, 0)
        self.TopColumnLayout.setObjectName("TopColumnLayout")
        spacerItem = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopColumnLayout.addItem(spacerItem)
        self.SearchArea = QtWidgets.QFrame(self.layoutWidget)
        self.SearchArea.setStyleSheet("border-radius: 10px;background-color:rgba(255,255,255,0.2)")
        self.SearchArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchArea.setObjectName("SearchArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SearchArea)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MusicNameLineEdit = QtWidgets.QLineEdit(self.SearchArea)
        self.MusicNameLineEdit.setStyleSheet("background-color:transparent")
        self.MusicNameLineEdit.setObjectName("MusicNameLineEdit")
        self.horizontalLayout_2.addWidget(self.MusicNameLineEdit)
        self.SearchButton = QtWidgets.QPushButton(self.SearchArea)
        self.SearchButton.setStyleSheet("background: transparent;")
        self.SearchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/files/static/image/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon1)
        self.SearchButton.setFlat(True)
        self.SearchButton.setObjectName("SearchButton")
        self.horizontalLayout_2.addWidget(self.SearchButton)
        self.TopColumnLayout.addWidget(self.SearchArea)
        spacerItem1 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopColumnLayout.addItem(spacerItem1)
        self.WindowControlLayout = QtWidgets.QHBoxLayout()
        self.WindowControlLayout.setObjectName("WindowControlLayout")
        self.MinimizeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.MinimizeButton.setStyleSheet("background: transparent;")
        self.MinimizeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/files/static/image/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MinimizeButton.setIcon(icon2)
        self.MinimizeButton.setFlat(True)
        self.MinimizeButton.setObjectName("MinimizeButton")
        self.WindowControlLayout.addWidget(self.MinimizeButton)
        self.CloseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.CloseButton.setStyleSheet("background: transparent;")
        self.CloseButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/files/static/image/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButton.setIcon(icon3)
        self.CloseButton.setFlat(True)
        self.CloseButton.setObjectName("CloseButton")
        self.WindowControlLayout.addWidget(self.CloseButton)
        self.TopColumnLayout.addLayout(self.WindowControlLayout)
        self.MusicSelectResultTable = QtWidgets.QTableView(self.CentralWidget)
        self.MusicSelectResultTable.setGeometry(QtCore.QRect(245, 100, 571, 361))
        self.MusicSelectResultTable.setStyleSheet("background: transparent;border: none;")
        self.MusicSelectResultTable.setObjectName("MusicSelectResultTable")
        MainWindow.setCentralWidget(self.CentralWidget)
        self.StatusBar = QtWidgets.QStatusBar(MainWindow)
        self.StatusBar.setObjectName("StatusBar")
        MainWindow.setStatusBar(self.StatusBar)

        self.retranslateUi(MainWindow)
        self.CloseButton.clicked.connect(MainWindow.close)
        self.MinimizeButton.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import Source_rc
