# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Player(object):
    def setupUi(self, Player):
        Player.setObjectName("Player")
        Player.resize(612, 79)
        self.PlaybackProgress = QtWidgets.QProgressBar(Player)
        self.PlaybackProgress.setGeometry(QtCore.QRect(100, 10, 361, 23))
        self.PlaybackProgress.setProperty("value", 24)
        self.PlaybackProgress.setObjectName("PlaybackProgress")
        self.widget = QtWidgets.QWidget(Player)
        self.widget.setGeometry(QtCore.QRect(160, 40, 239, 25))
        self.widget.setObjectName("widget")
        self.MainLayout = QtWidgets.QHBoxLayout(self.widget)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.Previous = QtWidgets.QPushButton(self.widget)
        self.Previous.setObjectName("Previous")
        self.MainLayout.addWidget(self.Previous)
        self.PlayAndPause = QtWidgets.QPushButton(self.widget)
        self.PlayAndPause.setObjectName("PlayAndPause")
        self.MainLayout.addWidget(self.PlayAndPause)
        self.Next = QtWidgets.QPushButton(self.widget)
        self.Next.setObjectName("Next")
        self.MainLayout.addWidget(self.Next)

        self.retranslateUi(Player)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        _translate = QtCore.QCoreApplication.translate
        Player.setWindowTitle(_translate("Player", "Form"))
        self.Previous.setText(_translate("Player", "PushButton"))
        self.PlayAndPause.setText(_translate("Player", "PushButton"))
        self.Next.setText(_translate("Player", "PushButton"))
